name: Bug Report
description: File a bug/issue
labels: ["bug", "triage", "needs testing"]
body:
  - type: markdown
    attributes:
      value: |
        ## Guidelines
        Please try to make sure that no issues of this same problem currently open
  - type: textarea
    attributes:
      label: Environment
      description: |
         - Provide information about the device the bug happened on.
      render: markdown
      value: |
      - Package Version:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug Description
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What was supposed to happen? If you are not sure, please state so.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: What did you do to make this problem happen? Try to be as thorough as possible.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Code Snippet
      description: A small code snippet displaying the issue would be useful
    validations:
      required: false
  - type: textarea
    attributes:
      label: Extras
      description: |
        Do you have anything else to add?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Checklist
      description: Please make sure you've completed all the steps in the checklist
      options:
      - label: I am not reporting a [security vulnerability](https://github.com/go-fresh/.github/security/policy)
        required: true
      - label: I have made sure this issue is not a duplicate
        required: true

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
