name: Question
description: If you have a question about this package and it doesn't fit in the other categories.
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Guidelines
        Please make sure that your suggestion isn't something already existing, and that it hasn't been suggested before.
  - type: textarea
    attributes:
      label: Question
      description: A concise description of your question.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Extras
      description: |
        Do you have anything else to add?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      description: Please make sure you've completed all the steps in the checklist
      options:
      - label: This is NOT a bug report or feature/support request.
        required: true
      - label: I have made sure this issue is not a duplicate
        required: true
      - label: This issue does not contain any sensitive information 
        required: true

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this question!
